services:
  portfolio:
    image: ghcr.io/bernes1/portfolio:latest
    container_name: portfolio
    ports:
      - "8080:80"
    restart: always
    networks:
      - webnet

networks:
  webnet:
    external: true