services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    networks:
      - webnet
    restart: always
    volumes:
      - ~/.thelounge:/var/opt/thelounge # bind lounge config from the host's file system

networks:
  webnet:
    external: true
